version: "3.9"

services:
  db:
    image: mongo:6.0
    container_name: pvba-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 5s
      retries: 5

  web:
    image: pvba-web:latest
    container_name: pvba-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - web_uploads:/app/data/image
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://db:27017/pvba

volumes:
  mongo_data:
  web_uploads:

