version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: pvba-nginx
    ports:
      - "80:80"
      - "443:443"   # bật khi có SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    networks:
      - public_net
      - private_net

  certbot:
    image: certbot/certbot
    container_name: pvba-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ""
    networks:
      - public_net

  web:
    image: pvba-web:latest
    container_name: pvba-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - web_uploads:/app/data/image
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "3000"
    networks:
      - private_net
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://pvba:helloworld123@db:27017/pvba?authSource=admin
      NEXTAUTH_SECRET: Helloworld12!@
      NEXTAUTH_URL: https://pvba.vn

  db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: pvba
      MONGO_INITDB_ROOT_PASSWORD: helloworld123
      MONGO_INITDB_DATABASE: pvba
    container_name: pvba-db
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 5s
      retries: 5
    networks:
      - private_net

networks:
  public_net:
    driver: bridge
  private_net:
    driver: bridge
    internal: true  

volumes:
  mongo_data:
  web_uploads:

